### ISSUE TITLE
Fails on MacOS 13 Ventura

### ISSUE THREAD

**Issue by rdrainville** [pietrodn/grpcio-mac-arm-build#6]
I receive the following error when attempting to install this on a Mac Studio (M1 Max): ERROR: grpcio-1.51.1-cp310-cp310-macosx_11_0_arm64.whl is not a supported wheel on this platform.

**Comment by pietrodn** [comment]
Hi, I have a MacBook Pro (M1 Pro) with macOS Ventura 13.2, and cannot reproduce. Unfortunately I don't have a Mac Studio.
How are you installing the wheel exactly?

Are you sure that you didn't install an Intel version of the Python interpreter, and you're running it with Rosetta 2?
You can check the architecture of your Python interpreter with:

```
python -c 'import platform; print(platform.platform())'
```

On my M1 Pro, I get:

```
macOS-13.2-arm64-arm-64bit
````

Also, if that's the case, `pip` should happily accept the official x86 wheel from `pip install grpcio`. I'd try that as well.

**Comment by rdrainville** [comment]
I attempted to install with the following command: 
pip install https://github.com/pietrodn/grpcio-mac-arm-build/releases/download/1.51.1/grpcio-1.51.1-cp310-cp310-macosx_11_0_arm64.whl

Re: the Python interpreter on my Mac Studio, I get: 
macOS-13.2.1-arm64-arm-64bit

**Comment by pietrodn** [comment]
Did you select the wheel for the correct Python version? I get your error when trying to install that wheel you linked (built for Python 3.10) on a Python 3.11 virtualenv. You can run `python -V` to get your current python version.

**Comment by rdrainville** [comment]
Ah, that's it—I selected the wrong wheel! Thank you!
